version: 3.3.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "3.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
environment:
  CoverityProjectToken:
    secure: pUUrynbyxCRpsAgGdKBVYDZCilwBmaWQ1Jg+rg5znr0=
  CoverityNotificationEmail:
    secure: m/ox72HU97EeJExWEFWx+0M9uov0cydn6E8mSaQzsQE=
build_script:
  - ps: (Get-Content HtmlSanitizer\project.json).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content HtmlSanitizer\project.json
  - dotnet restore
  - dotnet pack -c Release HtmlSanitizer
#test_script:
#  - nuget.exe install OpenCover -ExcludeVersion
#  - nuget.exe install NUnit.Runners -ExcludeVersion
#  - OpenCover\tools\OpenCover.Console.exe -register:user -filter:"+[HtmlSanitizer]*" -target:"NUnit.ConsoleRunner\tools\nunit3-console.exe" "-targetargs:/domain:single HtmlSanitizer.Tests\bin\release\HtmlSanitizer.Tests.dll" -returntargetcode -hideskipped:All -output:coverage.xml
#  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
#  - pip install codecov
#  - codecov -f "coverage.xml"
artifacts:
  - path: '**\*.nupkg'
