version: 4.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
  CoverityProjectToken:
    secure: pUUrynbyxCRpsAgGdKBVYDZCilwBmaWQ1Jg+rg5znr0=
  CoverityNotificationEmail:
    secure: m/ox72HU97EeJExWEFWx+0M9uov0cydn6E8mSaQzsQE=
build_script:
  - ps: (Get-Content src\HtmlSanitizer\HtmlSanitizer.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content src\HtmlSanitizer\HtmlSanitizer.csproj
  - dotnet restore
  - dotnet pack --include-symbols --include-source -c Release src\HtmlSanitizer
test_script:
  - dotnet test test\HtmlSanitizer.Tests\HtmlSanitizer.Tests.csproj
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="..\..\coverage.xml" test\HtmlSanitizer.Tests\HtmlSanitizer.Tests.csproj -f netcoreapp2.0
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'src\**\*.nupkg'
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "michael@ganss.org"
  - git config --global user.name "Michael Ganss"
  - git tag v%APPVEYOR_BUILD_VERSION%
  - git push origin --tags
